#!/bin/sh

###############################################################################
# Commmand for merging, pushing and deleting (locally and on origin) a branch #
# Takes one argument: branch                                                  #
# Usage: git mpsdelbr <branch>                                                #
# Usecase: You want to merge a branch in to your current branch,              #
# then push current branch and delete the merged branch locally and on origin #
###############################################################################

branch="$1"

git merge "$branch"
git push
git delbr "$branch"
