#!/bin/sh

##############################################################
# Commmand for deleting a branch locally and on origin       #
# Takes one argument: branch                                 #
# Usage: git delbr <branch>                                  #
# Usecase: You want to delete a branch locally and on origin #
##############################################################

branch="$1"

git branch -d "$branch"
git push origin --delete "$branch"
